# Generated by Django 5.2 on 2025-09-14 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0003_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
