# Generated by Django 5.2 on 2026-02-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0006_tasklog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
