# Generated by Django 5.2 on 2026-02-18 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0007_alter_tasklog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_week',
        ),
        migrations.RemoveField(
            model_name='task',
            name='weekly_progress',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='date',
            field=models.DateField(),
        ),
    ]
