# Generated by Django 5.2 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ToDo', '0008_remove_task_last_week_remove_task_weekly_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='weekly_progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
